// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/dyingvoid/urlshort/url/internal/domain"
)

// NewMockLinksRepository creates a new instance of MockLinksRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinksRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinksRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLinksRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLinksRepository is an autogenerated mock type for the LinksRepository type
type MockLinksRepository struct {
	mock.Mock
}

type MockLinksRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinksRepository) EXPECT() *MockLinksRepository_Expecter {
	return &MockLinksRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockLinksRepository
func (_mock *MockLinksRepository) Count(ctx context.Context, userID string) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinksRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockLinksRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockLinksRepository_Expecter) Count(ctx any, userID any) *MockLinksRepository_Count_Call {
	return &MockLinksRepository_Count_Call{Call: _e.mock.On("Count", ctx, userID)}
}

func (_c *MockLinksRepository_Count_Call) Run(run func(ctx context.Context, userID string)) *MockLinksRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinksRepository_Count_Call) Return(n int, err error) *MockLinksRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLinksRepository_Count_Call) RunAndReturn(run func(ctx context.Context, userID string) (int, error)) *MockLinksRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockLinksRepository
func (_mock *MockLinksRepository) Delete(ctx context.Context, shortCode string) error {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinksRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLinksRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockLinksRepository_Expecter) Delete(ctx any, shortCode any) *MockLinksRepository_Delete_Call {
	return &MockLinksRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, shortCode)}
}

func (_c *MockLinksRepository_Delete_Call) Run(run func(ctx context.Context, shortCode string)) *MockLinksRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinksRepository_Delete_Call) Return(err error) *MockLinksRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinksRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, shortCode string) error) *MockLinksRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByShortCode provides a mock function for the type MockLinksRepository
func (_mock *MockLinksRepository) GetByShortCode(ctx context.Context, shortCode string) (*domain.Link, error) {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortCode")
	}

	var r0 *domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Link, error)); ok {
		return returnFunc(ctx, shortCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Link); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinksRepository_GetByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByShortCode'
type MockLinksRepository_GetByShortCode_Call struct {
	*mock.Call
}

// GetByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockLinksRepository_Expecter) GetByShortCode(ctx any, shortCode any) *MockLinksRepository_GetByShortCode_Call {
	return &MockLinksRepository_GetByShortCode_Call{Call: _e.mock.On("GetByShortCode", ctx, shortCode)}
}

func (_c *MockLinksRepository_GetByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *MockLinksRepository_GetByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinksRepository_GetByShortCode_Call) Return(link *domain.Link, err error) *MockLinksRepository_GetByShortCode_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinksRepository_GetByShortCode_Call) RunAndReturn(run func(ctx context.Context, shortCode string) (*domain.Link, error)) *MockLinksRepository_GetByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockLinksRepository
func (_mock *MockLinksRepository) Insert(ctx context.Context, link *domain.Link) error {
	ret := _mock.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Link) error); ok {
		r0 = returnFunc(ctx, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinksRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockLinksRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - link *domain.Link
func (_e *MockLinksRepository_Expecter) Insert(ctx any, link any) *MockLinksRepository_Insert_Call {
	return &MockLinksRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, link)}
}

func (_c *MockLinksRepository_Insert_Call) Run(run func(ctx context.Context, link *domain.Link)) *MockLinksRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Link
		if args[1] != nil {
			arg1 = args[1].(*domain.Link)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinksRepository_Insert_Call) Return(err error) *MockLinksRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinksRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, link *domain.Link) error) *MockLinksRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockLinksRepository
func (_mock *MockLinksRepository) ListByUser(ctx context.Context, userID string, limit int, cursor string) ([]domain.Link, error) {
	ret := _mock.Called(ctx, userID, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) ([]domain.Link, error)); ok {
		return returnFunc(ctx, userID, limit, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) []domain.Link); ok {
		r0 = returnFunc(ctx, userID, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, string) error); ok {
		r1 = returnFunc(ctx, userID, limit, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinksRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockLinksRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - cursor string
func (_e *MockLinksRepository_Expecter) ListByUser(ctx any, userID any, limit any, cursor any) *MockLinksRepository_ListByUser_Call {
	return &MockLinksRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, limit, cursor)}
}

func (_c *MockLinksRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string, limit int, cursor string)) *MockLinksRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLinksRepository_ListByUser_Call) Return(links []domain.Link, err error) *MockLinksRepository_ListByUser_Call {
	_c.Call.Return(links, err)
	return _c
}

func (_c *MockLinksRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string, limit int, cursor string) ([]domain.Link, error)) *MockLinksRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
