// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/dyingvoid/urlshort/url/internal/domain"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// DecLinkCounter provides a mock function for the type MockCache
func (_mock *MockCache) DecLinkCounter(ctx context.Context, userID string) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DecLinkCounter")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_DecLinkCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecLinkCounter'
type MockCache_DecLinkCounter_Call struct {
	*mock.Call
}

// DecLinkCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCache_Expecter) DecLinkCounter(ctx any, userID any) *MockCache_DecLinkCounter_Call {
	return &MockCache_DecLinkCounter_Call{Call: _e.mock.On("DecLinkCounter", ctx, userID)}
}

func (_c *MockCache_DecLinkCounter_Call) Run(run func(ctx context.Context, userID string)) *MockCache_DecLinkCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_DecLinkCounter_Call) Return(n int, err error) *MockCache_DecLinkCounter_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCache_DecLinkCounter_Call) RunAndReturn(run func(ctx context.Context, userID string) (int, error)) *MockCache_DecLinkCounter_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function for the type MockCache
func (_mock *MockCache) DeleteLink(ctx context.Context, shortCode string) error {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type MockCache_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockCache_Expecter) DeleteLink(ctx any, shortCode any) *MockCache_DeleteLink_Call {
	return &MockCache_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, shortCode)}
}

func (_c *MockCache_DeleteLink_Call) Run(run func(ctx context.Context, shortCode string)) *MockCache_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_DeleteLink_Call) Return(err error) *MockCache_DeleteLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_DeleteLink_Call) RunAndReturn(run func(ctx context.Context, shortCode string) error) *MockCache_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetLink provides a mock function for the type MockCache
func (_mock *MockCache) GetLink(ctx context.Context, shortCode string) (*domain.Link, error) {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetLink")
	}

	var r0 *domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Link, error)); ok {
		return returnFunc(ctx, shortCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Link); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLink'
type MockCache_GetLink_Call struct {
	*mock.Call
}

// GetLink is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockCache_Expecter) GetLink(ctx any, shortCode any) *MockCache_GetLink_Call {
	return &MockCache_GetLink_Call{Call: _e.mock.On("GetLink", ctx, shortCode)}
}

func (_c *MockCache_GetLink_Call) Run(run func(ctx context.Context, shortCode string)) *MockCache_GetLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_GetLink_Call) Return(link *domain.Link, err error) *MockCache_GetLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockCache_GetLink_Call) RunAndReturn(run func(ctx context.Context, shortCode string) (*domain.Link, error)) *MockCache_GetLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkCounter provides a mock function for the type MockCache
func (_mock *MockCache) GetLinkCounter(ctx context.Context, userID string) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkCounter")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetLinkCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkCounter'
type MockCache_GetLinkCounter_Call struct {
	*mock.Call
}

// GetLinkCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCache_Expecter) GetLinkCounter(ctx any, userID any) *MockCache_GetLinkCounter_Call {
	return &MockCache_GetLinkCounter_Call{Call: _e.mock.On("GetLinkCounter", ctx, userID)}
}

func (_c *MockCache_GetLinkCounter_Call) Run(run func(ctx context.Context, userID string)) *MockCache_GetLinkCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_GetLinkCounter_Call) Return(n int, err error) *MockCache_GetLinkCounter_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCache_GetLinkCounter_Call) RunAndReturn(run func(ctx context.Context, userID string) (int, error)) *MockCache_GetLinkCounter_Call {
	_c.Call.Return(run)
	return _c
}

// IncLinkCounter provides a mock function for the type MockCache
func (_mock *MockCache) IncLinkCounter(ctx context.Context, userID string) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IncLinkCounter")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_IncLinkCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncLinkCounter'
type MockCache_IncLinkCounter_Call struct {
	*mock.Call
}

// IncLinkCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCache_Expecter) IncLinkCounter(ctx any, userID any) *MockCache_IncLinkCounter_Call {
	return &MockCache_IncLinkCounter_Call{Call: _e.mock.On("IncLinkCounter", ctx, userID)}
}

func (_c *MockCache_IncLinkCounter_Call) Run(run func(ctx context.Context, userID string)) *MockCache_IncLinkCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_IncLinkCounter_Call) Return(n int, err error) *MockCache_IncLinkCounter_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCache_IncLinkCounter_Call) RunAndReturn(run func(ctx context.Context, userID string) (int, error)) *MockCache_IncLinkCounter_Call {
	_c.Call.Return(run)
	return _c
}

// SetLink provides a mock function for the type MockCache
func (_mock *MockCache) SetLink(ctx context.Context, link *domain.Link, ttl time.Duration) error {
	ret := _mock.Called(ctx, link, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Link, time.Duration) error); ok {
		r0 = returnFunc(ctx, link, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SetLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLink'
type MockCache_SetLink_Call struct {
	*mock.Call
}

// SetLink is a helper method to define mock.On call
//   - ctx context.Context
//   - link *domain.Link
//   - ttl time.Duration
func (_e *MockCache_Expecter) SetLink(ctx any, link any, ttl any) *MockCache_SetLink_Call {
	return &MockCache_SetLink_Call{Call: _e.mock.On("SetLink", ctx, link, ttl)}
}

func (_c *MockCache_SetLink_Call) Run(run func(ctx context.Context, link *domain.Link, ttl time.Duration)) *MockCache_SetLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Link
		if args[1] != nil {
			arg1 = args[1].(*domain.Link)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_SetLink_Call) Return(err error) *MockCache_SetLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SetLink_Call) RunAndReturn(run func(ctx context.Context, link *domain.Link, ttl time.Duration) error) *MockCache_SetLink_Call {
	_c.Call.Return(run)
	return _c
}

// SetLinkCounter provides a mock function for the type MockCache
func (_mock *MockCache) SetLinkCounter(ctx context.Context, userID string, val int) error {
	ret := _mock.Called(ctx, userID, val)

	if len(ret) == 0 {
		panic("no return value specified for SetLinkCounter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, userID, val)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SetLinkCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLinkCounter'
type MockCache_SetLinkCounter_Call struct {
	*mock.Call
}

// SetLinkCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - val int
func (_e *MockCache_Expecter) SetLinkCounter(ctx any, userID any, val any) *MockCache_SetLinkCounter_Call {
	return &MockCache_SetLinkCounter_Call{Call: _e.mock.On("SetLinkCounter", ctx, userID, val)}
}

func (_c *MockCache_SetLinkCounter_Call) Run(run func(ctx context.Context, userID string, val int)) *MockCache_SetLinkCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_SetLinkCounter_Call) Return(err error) *MockCache_SetLinkCounter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SetLinkCounter_Call) RunAndReturn(run func(ctx context.Context, userID string, val int) error) *MockCache_SetLinkCounter_Call {
	_c.Call.Return(run)
	return _c
}
