// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/dyingvoid/shorturl/user/internal/domain"
)

// NewMockSessionsRepository creates a new instance of MockSessionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionsRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSessionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSessionsRepository is an autogenerated mock type for the SessionsRepository type
type MockSessionsRepository struct {
	mock.Mock
}

type MockSessionsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionsRepository) EXPECT() *MockSessionsRepository_Expecter {
	return &MockSessionsRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) CreateSession(ctx context.Context, userID uuid.UUID, expiresAt time.Time) (domain.Session, error) {
	ret := _mock.Called(ctx, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (domain.Session, error)); ok {
		return returnFunc(ctx, userID, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) domain.Session); ok {
		r0 = returnFunc(ctx, userID, expiresAt)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionsRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionsRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - expiresAt time.Time
func (_e *MockSessionsRepository_Expecter) CreateSession(ctx any, userID any, expiresAt any) *MockSessionsRepository_CreateSession_Call {
	return &MockSessionsRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, expiresAt)}
}

func (_c *MockSessionsRepository_CreateSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, expiresAt time.Time)) *MockSessionsRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_CreateSession_Call) Return(session domain.Session, err error) *MockSessionsRepository_CreateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionsRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, expiresAt time.Time) (domain.Session, error)) *MockSessionsRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) GetSession(ctx context.Context, id uuid.UUID) (domain.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionsRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionsRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionsRepository_Expecter) GetSession(ctx any, id any) *MockSessionsRepository_GetSession_Call {
	return &MockSessionsRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, id)}
}

func (_c *MockSessionsRepository_GetSession_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionsRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_GetSession_Call) Return(session domain.Session, err error) *MockSessionsRepository_GetSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionsRepository_GetSession_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Session, error)) *MockSessionsRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) RevokeSession(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionsRepository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockSessionsRepository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionsRepository_Expecter) RevokeSession(ctx any, id any) *MockSessionsRepository_RevokeSession_Call {
	return &MockSessionsRepository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, id)}
}

func (_c *MockSessionsRepository_RevokeSession_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionsRepository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_RevokeSession_Call) Return(err error) *MockSessionsRepository_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionsRepository_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSessionsRepository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}
