// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"

	"github.com/dyingvoid/shorturl/user/internal/domain"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// AccessTTL provides a mock function for the type MockTokenService
func (_mock *MockTokenService) AccessTTL() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessTTL")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTokenService_AccessTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessTTL'
type MockTokenService_AccessTTL_Call struct {
	*mock.Call
}

// AccessTTL is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) AccessTTL() *MockTokenService_AccessTTL_Call {
	return &MockTokenService_AccessTTL_Call{Call: _e.mock.On("AccessTTL")}
}

func (_c *MockTokenService_AccessTTL_Call) Run(run func()) *MockTokenService_AccessTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_AccessTTL_Call) Return(duration time.Duration) *MockTokenService_AccessTTL_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTokenService_AccessTTL_Call) RunAndReturn(run func() time.Duration) *MockTokenService_AccessTTL_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Issue(user domain.User, session domain.Session) (domain.TokenPair, error) {
	ret := _mock.Called(user, session)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 domain.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.User, domain.Session) (domain.TokenPair, error)); ok {
		return returnFunc(user, session)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.User, domain.Session) domain.TokenPair); ok {
		r0 = returnFunc(user, session)
	} else {
		r0 = ret.Get(0).(domain.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.User, domain.Session) error); ok {
		r1 = returnFunc(user, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenService_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - user domain.User
//   - session domain.Session
func (_e *MockTokenService_Expecter) Issue(user any, session any) *MockTokenService_Issue_Call {
	return &MockTokenService_Issue_Call{Call: _e.mock.On("Issue", user, session)}
}

func (_c *MockTokenService_Issue_Call) Run(run func(user domain.User, session domain.Session)) *MockTokenService_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.User
		if args[0] != nil {
			arg0 = args[0].(domain.User)
		}
		var arg1 domain.Session
		if args[1] != nil {
			arg1 = args[1].(domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_Issue_Call) Return(tokenPair domain.TokenPair, err error) *MockTokenService_Issue_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockTokenService_Issue_Call) RunAndReturn(run func(user domain.User, session domain.Session) (domain.TokenPair, error)) *MockTokenService_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAccess provides a mock function for the type MockTokenService
func (_mock *MockTokenService) ParseAccess(token string) (domain.TokenClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccess")
	}

	var r0 domain.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.TokenClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.TokenClaims); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(domain.TokenClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_ParseAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccess'
type MockTokenService_ParseAccess_Call struct {
	*mock.Call
}

// ParseAccess is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) ParseAccess(token any) *MockTokenService_ParseAccess_Call {
	return &MockTokenService_ParseAccess_Call{Call: _e.mock.On("ParseAccess", token)}
}

func (_c *MockTokenService_ParseAccess_Call) Run(run func(token string)) *MockTokenService_ParseAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_ParseAccess_Call) Return(tokenClaims domain.TokenClaims, err error) *MockTokenService_ParseAccess_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *MockTokenService_ParseAccess_Call) RunAndReturn(run func(token string) (domain.TokenClaims, error)) *MockTokenService_ParseAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefresh provides a mock function for the type MockTokenService
func (_mock *MockTokenService) ParseRefresh(token string) (domain.TokenClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefresh")
	}

	var r0 domain.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.TokenClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.TokenClaims); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(domain.TokenClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_ParseRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefresh'
type MockTokenService_ParseRefresh_Call struct {
	*mock.Call
}

// ParseRefresh is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) ParseRefresh(token any) *MockTokenService_ParseRefresh_Call {
	return &MockTokenService_ParseRefresh_Call{Call: _e.mock.On("ParseRefresh", token)}
}

func (_c *MockTokenService_ParseRefresh_Call) Run(run func(token string)) *MockTokenService_ParseRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_ParseRefresh_Call) Return(tokenClaims domain.TokenClaims, err error) *MockTokenService_ParseRefresh_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *MockTokenService_ParseRefresh_Call) RunAndReturn(run func(token string) (domain.TokenClaims, error)) *MockTokenService_ParseRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccess provides a mock function for the type MockTokenService
func (_mock *MockTokenService) RefreshAccess(claims domain.TokenClaims) (string, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccess")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.TokenClaims) (string, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.TokenClaims) string); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.TokenClaims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_RefreshAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccess'
type MockTokenService_RefreshAccess_Call struct {
	*mock.Call
}

// RefreshAccess is a helper method to define mock.On call
//   - claims domain.TokenClaims
func (_e *MockTokenService_Expecter) RefreshAccess(claims any) *MockTokenService_RefreshAccess_Call {
	return &MockTokenService_RefreshAccess_Call{Call: _e.mock.On("RefreshAccess", claims)}
}

func (_c *MockTokenService_RefreshAccess_Call) Run(run func(claims domain.TokenClaims)) *MockTokenService_RefreshAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.TokenClaims
		if args[0] != nil {
			arg0 = args[0].(domain.TokenClaims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_RefreshAccess_Call) Return(s string, err error) *MockTokenService_RefreshAccess_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_RefreshAccess_Call) RunAndReturn(run func(claims domain.TokenClaims) (string, error)) *MockTokenService_RefreshAccess_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTTL provides a mock function for the type MockTokenService
func (_mock *MockTokenService) RefreshTTL() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshTTL")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTokenService_RefreshTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTTL'
type MockTokenService_RefreshTTL_Call struct {
	*mock.Call
}

// RefreshTTL is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) RefreshTTL() *MockTokenService_RefreshTTL_Call {
	return &MockTokenService_RefreshTTL_Call{Call: _e.mock.On("RefreshTTL")}
}

func (_c *MockTokenService_RefreshTTL_Call) Run(run func()) *MockTokenService_RefreshTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_RefreshTTL_Call) Return(duration time.Duration) *MockTokenService_RefreshTTL_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTokenService_RefreshTTL_Call) RunAndReturn(run func() time.Duration) *MockTokenService_RefreshTTL_Call {
	_c.Call.Return(run)
	return _c
}
