// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/dyingvoid/shorturl/user/internal/domain"
)

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) CreateUser(ctx context.Context, email domain.Email, passwordHash string) (domain.User, error) {
	ret := _mock.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Email, string) (domain.User, error)); ok {
		return returnFunc(ctx, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Email, string) domain.User); ok {
		r0 = returnFunc(ctx, email, passwordHash)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Email, string) error); ok {
		r1 = returnFunc(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsersRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email domain.Email
//   - passwordHash string
func (_e *MockUsersRepository_Expecter) CreateUser(ctx any, email any, passwordHash any) *MockUsersRepository_CreateUser_Call {
	return &MockUsersRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, passwordHash)}
}

func (_c *MockUsersRepository_CreateUser_Call) Run(run func(ctx context.Context, email domain.Email, passwordHash string)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Email
		if args[1] != nil {
			arg1 = args[1].(domain.Email)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) Return(user domain.User, err error) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, email domain.Email, passwordHash string) (domain.User, error)) *MockUsersRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetLimit provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetLimit(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLimit")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimit'
type MockUsersRepository_GetLimit_Call struct {
	*mock.Call
}

// GetLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUsersRepository_Expecter) GetLimit(ctx any, userID any) *MockUsersRepository_GetLimit_Call {
	return &MockUsersRepository_GetLimit_Call{Call: _e.mock.On("GetLimit", ctx, userID)}
}

func (_c *MockUsersRepository_GetLimit_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUsersRepository_GetLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetLimit_Call) Return(n int, err error) *MockUsersRepository_GetLimit_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUsersRepository_GetLimit_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int, error)) *MockUsersRepository_GetLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByEmail(ctx context.Context, email domain.Email) (domain.User, string, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 domain.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Email) (domain.User, string, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Email) domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Email) string); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.Email) error); ok {
		r2 = returnFunc(ctx, email)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUsersRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUsersRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email domain.Email
func (_e *MockUsersRepository_Expecter) GetUserByEmail(ctx any, email any) *MockUsersRepository_GetUserByEmail_Call {
	return &MockUsersRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUsersRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email domain.Email)) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Email
		if args[1] != nil {
			arg1 = args[1].(domain.Email)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByEmail_Call) Return(user domain.User, s string, err error) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Return(user, s, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email domain.Email) (domain.User, string, error)) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}
